apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java-sample-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-java-sample-webapp
  template:
    metadata:
      labels:
        app: docker-java-sample-webapp
    spec:
      containers:
      - name: docker-java-sample-webapp
        image: subbu25022002/docker-java-sample-webapp:latest
        ports:
        - containerPort: 8080
